// 战役模式关卡数据
export const CAMPAIGN_STAGES = [
  {
    id: 1,
    title: '第一关：墨境初醒',
    scene: 'void',
    enemy: ['swordsman', 'archer'],
    difficulty: 'easy',
    intro: '墨境世界的边缘，一名流浪剑士与弓手拦住了你的去路。\n"外来者，此路不通。"',
    outro: '剑士倒下，弓手逃窜。\n墨境的大门，向你敞开了。',
  },
  {
    id: 2,
    title: '第二关：赤焰试炼',
    scene: 'lava',
    enemy: ['berserker', 'guardian'],
    difficulty: 'easy',
    intro: '赤焰熔岩之地，守卫着古老的熔炉。\n狂战士咆哮："用你的血，来祭奠这片火海！"',
    outro: '烈焰熄灭，守卫沉默。\n熔炉的秘密，等待着你去揭开。',
  },
  {
    id: 3,
    title: '第三关：灵泉守护者',
    scene: 'spring',
    enemy: ['priest', 'mage'],
    difficulty: 'normal',
    intro: '碧蓝灵泉深处，两名守护者感知到了你的闯入。\n法师冷声道："灵泉的力量，不属于你这样的人。"',
    outro: '灵泉的涟漪渐渐平息。\n牧师低语："也许……你才是命中注定的那个人。"',
  },
  {
    id: 4,
    title: '第四关：暗影双煞',
    scene: 'void',
    enemy: ['assassin', 'warlock'],
    difficulty: 'normal',
    intro: '墨色虚空中，两道黑影悄然现身。\n刺客嗤笑："你的影子，将成为我们的玩具。"',
    outro: '暗影消散，虚空归于寂静。\n术士临死前留下一句话："……墨皇已经知道你来了。"',
  },
  {
    id: 5,
    title: '第五关：熔岩双将',
    scene: 'lava',
    enemy: ['berserker', 'swordsman'],
    difficulty: 'normal',
    intro: '熔岩深处，墨皇的两名先锋将领严阵以待。\n"墨皇有令——格杀勿论。"',
    outro: '两将败北，熔岩中传来遥远的怒吼。\n墨皇的王座，已近在咫尺。',
  },
  {
    id: 6,
    title: '第六关：灵泉四卫',
    scene: 'spring',
    enemy: ['guardian', 'archer'],
    difficulty: 'hard',
    intro: '灵泉的最后防线，由最精锐的卫士把守。\n守卫举盾："就算你过了前五关，也休想再进一步！"',
    outro: '防线崩溃，灵泉之水涌向远方。\n前方，是墨皇的宫殿。',
  },
  {
    id: 7,
    title: '第七关：墨皇近卫',
    scene: 'void',
    enemy: ['warlock', 'priest'],
    difficulty: 'hard',
    intro: '墨皇宫殿门前，两名近卫展开了最后的阻拦。\n术士低吟："墨皇赐予我们力量，你无法通过。"',
    outro: '近卫倒下，宫殿大门缓缓开启。\n黑暗中，一道威严的声音传来："……终于来了。"',
  },
  {
    id: 8,
    title: '最终关：墨皇决战',
    scene: 'lava',
    enemy: ['mage', 'assassin'],
    difficulty: 'hard',
    intro: '墨皇现身，身旁是他最强的两名战士。\n"你的旅途，到此为止。墨境，永远是我的。"\n\n——这是最后的决战。',
    outro: '墨皇的力量消散，墨境的天空第一次出现了光芒。\n\n"也许……墨境需要的，从来不是统治，而是自由。"\n\n【战役通关！墨境之战，你赢了。】',
  },
];
